source 'http://rubygems.org'

gem 'rspec'
gem 'timecop'
gem 'awesome_print'
gem 'highline', '~> 1.6.12'
gem 'hashie', '~> 1.2.0'
gem 'twitter', '~> 2.5.0'
gem 'tweetstream', '~> 1.1.3'
gem 'yajl-ruby', '~> 1.1.0'
gem 'horai', '~> 0.7.1'
gem 'standalone_migrations', '~> 1.0.10'
gem 'activerecord', '~> 3.2.5'
gem 'sqlite3', '~> 1.3.6'
