source 'http://rubygems.org'

#gem 'userstream', '~> 1.2.2'
#gem 'activesupport', '~> 3.2.3', require: 'active_support/core_ext'
gem 'rspec'
gem 'timecop'
gem 'awesome_print'
gem 'hashie'
gem 'tweetstream'
gem 'yajl-ruby'
gem 'twitter'
gem 'horai'
gem 'standalone_migrations'
gem 'activerecord'
gem 'sqlite3'
gem 'highline'
